# -*- coding: utf-8 -*-
"""accessible-image-voice-assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14qFTvWnxJqBxQuwkAgALQr1ejzBX9-YT
"""

!pip install transformers accelerate torch pillow gtts qwen-vl-utils

from transformers import Qwen2VLForConditionalGeneration, AutoProcessor
import torch

processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-2B-Instruct")
model = Qwen2VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2-VL-2B-Instruct",
    torch_dtype=torch.float16,
    low_cpu_mem_usage=True
).to("cuda")

from google.colab import files
uploaded = files.upload()

from PIL import Image

def get_caption(image_path):
    image = Image.open(image_path)
    prompt = "[INST] <image>\nDescribe this image in detail. [/INST]"
    inputs = processor(text=prompt, images=image, return_tensors="pt").to("cuda")
    output = model.generate(**inputs, max_new_tokens=100)
    return processor.decode(output[0], skip_special_tokens=True)

def ask_question(image_path, question):
    image = Image.open(image_path)
    prompt = f"[INST] <image>\n{question} [/INST]"
    inputs = processor(text=prompt, images=image, return_tensors="pt").to("cuda")
    output = model.generate(**inputs, max_new_tokens=50)
    return processor.decode(output[0], skip_special_tokens=True)

from PIL import Image

def get_caption(image_path):
    image = Image.open(image_path)
    messages = [{"role": "user", "content": [
        {"type": "image"},
        {"type": "text", "text": "Describe this image in detail."}
    ]}]
    text_prompt = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = processor(text=[text_prompt], images=[image], return_tensors="pt").to("cuda")
    output = model.generate(**inputs, max_new_tokens=100)
    result = processor.batch_decode(output, skip_special_tokens=True)[0]
    return result.split("assistant\n")[-1].strip()

def ask_question(image_path, question):
    image = Image.open(image_path)
    messages = [{"role": "user", "content": [
        {"type": "image"},
        {"type": "text", "text": question}
    ]}]
    text_prompt = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = processor(text=[text_prompt], images=[image], return_tensors="pt").to("cuda")
    output = model.generate(**inputs, max_new_tokens=50)
    result = processor.batch_decode(output, skip_special_tokens=True)[0]
    return result.split("assistant\n")[-1].strip()

print(get_caption("astronaut.jpg"))

print(ask_question("astronaut.jpg", "What color is the suit?"))

print(get_caption("coins.jpg"))
print(ask_question("coins.jpg", "How many coins are there?"))

def answer_with_confidence_check(image_path, question):
    answer1 = ask_question(image_path, question)
    answer2 = ask_question(image_path, question + " Please be specific.")
    if answer1.strip().lower()[:30] != answer2.strip().lower()[:30]:
        return f"CLARIFYING QUESTION NEEDED: Could you clarify what you mean by '{question}'?"
    else:
        return answer1

print(answer_with_confidence_check("astronaut.jpg", "What is happening in this image?"))

print(answer_with_confidence_check("hubble_deep_field.jpg", "What is the main object in this image?"))

from gtts import gTTS
from IPython.display import Audio

def speak_text(text, filename="output_audio.mp3"):
    tts = gTTS(text)
    tts.save(filename)
    return filename

caption = get_caption("astronaut.jpg")
audio_file = speak_text(caption)
Audio(audio_file)

import pandas as pd

results = []
for i, filename in enumerate(uploaded.keys()):
    caption = get_caption(filename)
    vqa_answer = answer_with_confidence_check(filename, "What is happening in this image?")
    audio_file = speak_text(caption, f"caption_{i}.mp3")

    results.append({
        "image": filename,
        "caption": caption,
        "vqa_answer": vqa_answer,
        "audio_file": audio_file
    })
    print(f"Image: {filename}\nCaption: {caption}\nVQA: {vqa_answer}\nAudio saved: {audio_file}\n---")

df = pd.DataFrame(results)
df.to_csv("results.csv", index=False)

from google.colab import files
files.download("results.csv")

files.download("caption_0.mp3")

